//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Mame
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MEntities : Entity
    {
        public MEntities()
            : base("name=MEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disk> Disks { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Rom> Roms { get; set; }
        public virtual DbSet<RomFile> RomFiles { get; set; }
    }
}
