//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Mame
{
    using Microsoft.EntityFrameworkCore;
    
    public partial class Entities : DbContext
    {
        //public Entities()
        //    : base("name=Entities")
        //{
        //}
    
    
        public virtual DbSet<Disk> Disks { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Rom> Roms { get; set; }
        public virtual DbSet<RomFile> RomFiles { get; set; }
    }
}
