//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGDBRELEAS
    {
        public long releaseID { get; set; }
        public long romID { get; set; }
        public string releaseTitleName { get; set; }
        public Nullable<long> regionLocalizedID { get; set; }
        public string TEMPregionLocalizedName { get; set; }
        public string TEMPsystemShortName { get; set; }
        public string TEMPsystemName { get; set; }
        public string releaseCoverFront { get; set; }
        public string releaseCoverBack { get; set; }
        public string releaseCoverCart { get; set; }
        public string releaseCoverDisc { get; set; }
        public string releaseDescription { get; set; }
        public string releaseDeveloper { get; set; }
        public string releasePublisher { get; set; }
        public string releaseGenre { get; set; }
        public string releaseDate { get; set; }
        public string releaseReferenceURL { get; set; }
        public string releaseReferenceImageURL { get; set; }
    
        public virtual VGDBREGION VGDBREGION { get; set; }
        public virtual VGDBROM VGDBROM { get; set; }
    }
}
