//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Core.Mame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rom()
        {
            this.RomFiles = new HashSet<RomFile>();
            this.Machines = new HashSet<Machine>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public string CRC { get; set; }
        public Nullable<long> Size { get; set; }
        public string Status { get; set; }
        public bool Optional { get; set; }
        public bool Unknown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RomFile> RomFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machines { get; set; }
    }
}
