// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Robin
{
    public partial class RobinDataContextModel
    {
        partial void Initialize()
        {
            var collectionGame = CollectionGameEntityType.Create(this);
            var collectionRelease = CollectionReleaseEntityType.Create(this);
            var corePlatform = CorePlatformEntityType.Create(this);
            var platformEmulator = PlatformEmulatorEntityType.Create(this);
            var collection = CollectionEntityType.Create(this);
            var core = CoreEntityType.Create(this);
            var emulator = EmulatorEntityType.Create(this);
            var game = GameEntityType.Create(this);
            var gbgame = GbgameEntityType.Create(this);
            var gbplatform = GbplatformEntityType.Create(this);
            var gbrelease = GbreleaseEntityType.Create(this);
            var gdbplatform = GdbplatformEntityType.Create(this);
            var gdbrelease = GdbreleaseEntityType.Create(this);
            var language = LanguageEntityType.Create(this);
            var lbgame = LbgameEntityType.Create(this);
            var lbimage = LbimageEntityType.Create(this);
            var lbplatform = LbplatformEntityType.Create(this);
            var lbrelease = LbreleaseEntityType.Create(this);
            var match = MatchEntityType.Create(this);
            var ovgplatform = OvgplatformEntityType.Create(this);
            var ovgrelease = OvgreleaseEntityType.Create(this);
            var platform = PlatformEntityType.Create(this);
            var region = RegionEntityType.Create(this);
            var release = ReleaseEntityType.Create(this);
            var rom = RomEntityType.Create(this);
            var url = UrlEntityType.Create(this);

            CollectionGameEntityType.CreateForeignKey1(collectionGame, collection);
            CollectionGameEntityType.CreateForeignKey2(collectionGame, game);
            CollectionReleaseEntityType.CreateForeignKey1(collectionRelease, collection);
            CollectionReleaseEntityType.CreateForeignKey2(collectionRelease, release);
            CorePlatformEntityType.CreateForeignKey1(corePlatform, core);
            CorePlatformEntityType.CreateForeignKey2(corePlatform, platform);
            PlatformEmulatorEntityType.CreateForeignKey1(platformEmulator, emulator);
            PlatformEmulatorEntityType.CreateForeignKey2(platformEmulator, platform);
            CoreEntityType.CreateForeignKey1(core, emulator);
            GbgameEntityType.CreateForeignKey1(gbgame, gbplatform);
            GbreleaseEntityType.CreateForeignKey1(gbrelease, gbgame);
            GbreleaseEntityType.CreateForeignKey2(gbrelease, gbplatform);
            GbreleaseEntityType.CreateForeignKey3(gbrelease, region);
            GdbreleaseEntityType.CreateForeignKey1(gdbrelease, gdbplatform);
            LbgameEntityType.CreateForeignKey1(lbgame, lbplatform);
            LbimageEntityType.CreateForeignKey1(lbimage, lbrelease);
            LbreleaseEntityType.CreateForeignKey1(lbrelease, lbgame);
            LbreleaseEntityType.CreateForeignKey2(lbrelease, region);
            OvgreleaseEntityType.CreateForeignKey1(ovgrelease, ovgplatform);
            OvgreleaseEntityType.CreateForeignKey2(ovgrelease, region);
            PlatformEntityType.CreateForeignKey1(platform, gbplatform);
            PlatformEntityType.CreateForeignKey2(platform, gdbplatform);
            PlatformEntityType.CreateForeignKey3(platform, lbplatform);
            PlatformEntityType.CreateForeignKey4(platform, emulator);
            ReleaseEntityType.CreateForeignKey1(release, game);
            ReleaseEntityType.CreateForeignKey2(release, gbrelease);
            ReleaseEntityType.CreateForeignKey3(release, gdbrelease);
            ReleaseEntityType.CreateForeignKey4(release, lbrelease);
            ReleaseEntityType.CreateForeignKey5(release, lbgame);
            ReleaseEntityType.CreateForeignKey6(release, ovgrelease);
            ReleaseEntityType.CreateForeignKey7(release, platform);
            ReleaseEntityType.CreateForeignKey8(release, region);
            ReleaseEntityType.CreateForeignKey9(release, rom);

            CollectionEntityType.CreateSkipNavigation1(collection, game, collectionGame);
            CollectionEntityType.CreateSkipNavigation2(collection, release, collectionRelease);
            CoreEntityType.CreateSkipNavigation1(core, platform, corePlatform);
            EmulatorEntityType.CreateSkipNavigation1(emulator, platform, platformEmulator);
            GameEntityType.CreateSkipNavigation1(game, collection, collectionGame);
            PlatformEntityType.CreateSkipNavigation1(platform, core, corePlatform);
            PlatformEntityType.CreateSkipNavigation2(platform, emulator, platformEmulator);
            ReleaseEntityType.CreateSkipNavigation1(release, collection, collectionRelease);

            CollectionGameEntityType.CreateAnnotations(collectionGame);
            CollectionReleaseEntityType.CreateAnnotations(collectionRelease);
            CorePlatformEntityType.CreateAnnotations(corePlatform);
            PlatformEmulatorEntityType.CreateAnnotations(platformEmulator);
            CollectionEntityType.CreateAnnotations(collection);
            CoreEntityType.CreateAnnotations(core);
            EmulatorEntityType.CreateAnnotations(emulator);
            GameEntityType.CreateAnnotations(game);
            GbgameEntityType.CreateAnnotations(gbgame);
            GbplatformEntityType.CreateAnnotations(gbplatform);
            GbreleaseEntityType.CreateAnnotations(gbrelease);
            GdbplatformEntityType.CreateAnnotations(gdbplatform);
            GdbreleaseEntityType.CreateAnnotations(gdbrelease);
            LanguageEntityType.CreateAnnotations(language);
            LbgameEntityType.CreateAnnotations(lbgame);
            LbimageEntityType.CreateAnnotations(lbimage);
            LbplatformEntityType.CreateAnnotations(lbplatform);
            LbreleaseEntityType.CreateAnnotations(lbrelease);
            MatchEntityType.CreateAnnotations(match);
            OvgplatformEntityType.CreateAnnotations(ovgplatform);
            OvgreleaseEntityType.CreateAnnotations(ovgrelease);
            PlatformEntityType.CreateAnnotations(platform);
            RegionEntityType.CreateAnnotations(region);
            ReleaseEntityType.CreateAnnotations(release);
            RomEntityType.CreateAnnotations(rom);
            UrlEntityType.CreateAnnotations(url);

            AddAnnotation("ProductVersion", "6.0.1");
        }
    }
}
