// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Robin
{
    [DbContext(typeof(RobinDataContext))]
    public partial class RobinDataContextModel : RuntimeModel
    {
        static RobinDataContextModel()
        {
            var model = new RobinDataContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static RobinDataContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
