using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Mapping;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Infrastructure.MappingViews;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Robin
{
	partial class DebugStuff
	{
		string header = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

";

		public static void GenerateViews(DbContext context)
		{
			var objectContext = ((IObjectContextAdapter)context).ObjectContext;
			var mappingCollection = (StorageMappingItemCollection)objectContext.MetadataWorkspace.GetItemCollection(DataSpace.CSSpace);

			List<EdmSchemaError> errors = new List<EdmSchemaError>();
			Dictionary<EntitySetBase, DbMappingView> dd = mappingCollection.GenerateViews(errors);

			string hashValues = mappingCollection.ComputeMappingHashValue();

			

		}


	}
}
