//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseFilterPublisher {
            get {
                return ((string)(this["ReleaseFilterPublisher"]));
            }
            set {
                this["ReleaseFilterPublisher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseFilterGenre {
            get {
                return ((string)(this["ReleaseFilterGenre"]));
            }
            set {
                this["ReleaseFilterGenre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseFilterPlayers {
            get {
                return ((string)(this["ReleaseFilterPlayers"]));
            }
            set {
                this["ReleaseFilterPlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseFilterPlatform {
            get {
                return ((string)(this["ReleaseFilterPlatform"]));
            }
            set {
                this["ReleaseFilterPlatform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseFilterRegions {
            get {
                return ((string)(this["ReleaseFilterRegions"]));
            }
            set {
                this["ReleaseFilterRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseFilterYear {
            get {
                return ((string)(this["ReleaseFilterYear"]));
            }
            set {
                this["ReleaseFilterYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> ReleaseFilterIsCrap {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["ReleaseFilterIsCrap"]));
            }
            set {
                this["ReleaseFilterIsCrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> ReleaseFilterIncluded {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["ReleaseFilterIncluded"]));
            }
            set {
                this["ReleaseFilterIncluded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> ReleaseFilterUnlicensed {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["ReleaseFilterUnlicensed"]));
            }
            set {
                this["ReleaseFilterUnlicensed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFilterPublisher {
            get {
                return ((string)(this["GameFilterPublisher"]));
            }
            set {
                this["GameFilterPublisher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFilterGenre {
            get {
                return ((string)(this["GameFilterGenre"]));
            }
            set {
                this["GameFilterGenre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFilterPlayers {
            get {
                return ((string)(this["GameFilterPlayers"]));
            }
            set {
                this["GameFilterPlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFilterPlatform {
            get {
                return ((string)(this["GameFilterPlatform"]));
            }
            set {
                this["GameFilterPlatform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFilterRegions {
            get {
                return ((string)(this["GameFilterRegions"]));
            }
            set {
                this["GameFilterRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFilterYear {
            get {
                return ((string)(this["GameFilterYear"]));
            }
            set {
                this["GameFilterYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> GameFilterIsCrap {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["GameFilterIsCrap"]));
            }
            set {
                this["GameFilterIsCrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> GameFilterIncluded {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["GameFilterIncluded"]));
            }
            set {
                this["GameFilterIncluded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> GameFilterUnlicensed {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["GameFilterUnlicensed"]));
            }
            set {
                this["GameFilterUnlicensed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlatformFilterType {
            get {
                return ((string)(this["PlatformFilterType"]));
            }
            set {
                this["PlatformFilterType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlatformFilterGeneration {
            get {
                return ((string)(this["PlatformFilterGeneration"]));
            }
            set {
                this["PlatformFilterGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlatformFilterDeveloper {
            get {
                return ((string)(this["PlatformFilterDeveloper"]));
            }
            set {
                this["PlatformFilterDeveloper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlatformFilterManufacturer {
            get {
                return ((string)(this["PlatformFilterManufacturer"]));
            }
            set {
                this["PlatformFilterManufacturer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlatformFilterMedia {
            get {
                return ((string)(this["PlatformFilterMedia"]));
            }
            set {
                this["PlatformFilterMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlatformFilterYear {
            get {
                return ((string)(this["PlatformFilterYear"]));
            }
            set {
                this["PlatformFilterYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> PlatformFilterIsCrap {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["PlatformFilterIsCrap"]));
            }
            set {
                this["PlatformFilterIsCrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> PlatformFilterIncluded {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["PlatformFilterIncluded"]));
            }
            set {
                this["PlatformFilterIncluded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> PlatformFilterPreferred {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["PlatformFilterPreferred"]));
            }
            set {
                this["PlatformFilterPreferred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmulatorFilterPlatform {
            get {
                return ((string)(this["EmulatorFilterPlatform"]));
            }
            set {
                this["EmulatorFilterPlatform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> EmulatorFilterIncluded {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["EmulatorFilterIncluded"]));
            }
            set {
                this["EmulatorFilterIncluded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> EmulatorFilterIsCrap {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["EmulatorFilterIsCrap"]));
            }
            set {
                this["EmulatorFilterIsCrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayNonGames {
            get {
                return ((bool)(this["DisplayNonGames"]));
            }
            set {
                this["DisplayNonGames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayAdult {
            get {
                return ((bool)(this["DisplayAdult"]));
            }
            set {
                this["DisplayAdult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCrap {
            get {
                return ((bool)(this["DisplayCrap"]));
            }
            set {
                this["DisplayCrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayNotIncluded {
            get {
                return ((bool)(this["DisplayNotIncluded"]));
            }
            set {
                this["DisplayNotIncluded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> ReleaseFilterIsGame {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["ReleaseFilterIsGame"]));
            }
            set {
                this["ReleaseFilterIsGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> ReleaseFilterAdult {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["ReleaseFilterAdult"]));
            }
            set {
                this["ReleaseFilterAdult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> GameFilterIsGame {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["GameFilterIsGame"]));
            }
            set {
                this["GameFilterIsGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> GameFilterAdult {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["GameFilterAdult"]));
            }
            set {
                this["GameFilterAdult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortGamesRandom {
            get {
                return ((bool)(this["SortGamesRandom"]));
            }
            set {
                this["SortGamesRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> GameFilterIsMess {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["GameFilterIsMess"]));
            }
            set {
                this["GameFilterIsMess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayMess {
            get {
                return ((bool)(this["DisplayMess"]));
            }
            set {
                this["DisplayMess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DisplayChoice {
            get {
                return ((int)(this["DisplayChoice"]));
            }
            set {
                this["DisplayChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrapePlatformBanner {
            get {
                return ((bool)(this["ScrapePlatformBanner"]));
            }
            set {
                this["ScrapePlatformBanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrapePlatformBoxBack {
            get {
                return ((bool)(this["ScrapePlatformBoxBack"]));
            }
            set {
                this["ScrapePlatformBoxBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrapePlatformBoxFront {
            get {
                return ((bool)(this["ScrapePlatformBoxFront"]));
            }
            set {
                this["ScrapePlatformBoxFront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrapePlatformConsole {
            get {
                return ((bool)(this["ScrapePlatformConsole"]));
            }
            set {
                this["ScrapePlatformConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrapePlatformController {
            get {
                return ((bool)(this["ScrapePlatformController"]));
            }
            set {
                this["ScrapePlatformController"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrapeReleaseBanner {
            get {
                return ((bool)(this["ScrapeReleaseBanner"]));
            }
            set {
                this["ScrapeReleaseBanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrapeReleaseBoxBack {
            get {
                return ((bool)(this["ScrapeReleaseBoxBack"]));
            }
            set {
                this["ScrapeReleaseBoxBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrapeReleaseBoxFront {
            get {
                return ((bool)(this["ScrapeReleaseBoxFront"]));
            }
            set {
                this["ScrapeReleaseBoxFront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrapeReleaseLogo {
            get {
                return ((bool)(this["ScrapeReleaseLogo"]));
            }
            set {
                this["ScrapeReleaseLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrapeReleaseScreen {
            get {
                return ((bool)(this["ScrapeReleaseScreen"]));
            }
            set {
                this["ScrapeReleaseScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> GameFilterIsBeaten {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["GameFilterIsBeaten"]));
            }
            set {
                this["GameFilterIsBeaten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.Boolean> ReleaseFilterIsBeaten {
            get {
                return ((global::System.Nullable<System.Boolean>)(this["ReleaseFilterIsBeaten"]));
            }
            set {
                this["ReleaseFilterIsBeaten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<long> RecentFileIDs {
            get {
                return ((global::System.Collections.Generic.List<long>)(this["RecentFileIDs"]));
            }
            set {
                this["RecentFileIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RecentFileLimit {
            get {
                return ((int)(this["RecentFileLimit"]));
            }
            set {
                this["RecentFileLimit"] = value;
            }
        }
    }
}
