//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenVGDBEntities : DbContext
    {
        public OpenVGDBEntities()
            : base("name=OpenVGDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VGDBPLATFORM> VGDBPLATFORMS { get; set; }
        public virtual DbSet<VGDBREGION> VGDBREGIONS { get; set; }
        public virtual DbSet<VGDBRELEAS> VGDBRELEASES { get; set; }
        public virtual DbSet<VGDBROM> VGDBROMS { get; set; }
    }
}
