//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class URL : INotifyPropertyChanged
    {
        private long _iD;
    	public long ID 
    	{ 
    		get { return _iD; } 
    		set { _iD = value; OnPropertyChanged("ID"); } 
    	}
    
        private string _boxFront;
    	public string BoxFront 
    	{ 
    		get { return _boxFront; } 
    		set { _boxFront = value; OnPropertyChanged("BoxFront"); } 
    	}
    
        private string _boxBack;
    	public string BoxBack 
    	{ 
    		get { return _boxBack; } 
    		set { _boxBack = value; OnPropertyChanged("BoxBack"); } 
    	}
    
        private string _box3D;
    	public string Box3D 
    	{ 
    		get { return _box3D; } 
    		set { _box3D = value; OnPropertyChanged("Box3D"); } 
    	}
    
        private string _screen;
    	public string Screen 
    	{ 
    		get { return _screen; } 
    		set { _screen = value; OnPropertyChanged("Screen"); } 
    	}
    
        private string _logo;
    	public string Logo 
    	{ 
    		get { return _logo; } 
    		set { _logo = value; OnPropertyChanged("Logo"); } 
    	}
    
        private string _banner;
    	public string Banner 
    	{ 
    		get { return _banner; } 
    		set { _banner = value; OnPropertyChanged("Banner"); } 
    	}
    
        private string _cartridge;
    	public string Cartridge 
    	{ 
    		get { return _cartridge; } 
    		set { _cartridge = value; OnPropertyChanged("Cartridge"); } 
    	}
    
        private string _cartridge3D;
    	public string Cartridge3D 
    	{ 
    		get { return _cartridge3D; } 
    		set { _cartridge3D = value; OnPropertyChanged("Cartridge3D"); } 
    	}
    
        private string _marquee;
    	public string Marquee 
    	{ 
    		get { return _marquee; } 
    		set { _marquee = value; OnPropertyChanged("Marquee"); } 
    	}
    
        private string _controlPanel;
    	public string ControlPanel 
    	{ 
    		get { return _controlPanel; } 
    		set { _controlPanel = value; OnPropertyChanged("ControlPanel"); } 
    	}
    
        private string _video;
    	public string Video 
    	{ 
    		get { return _video; } 
    		set { _video = value; OnPropertyChanged("Video"); } 
    	}
    
        private string _wiki;
    	public string Wiki 
    	{ 
    		get { return _wiki; } 
    		set { _wiki = value; OnPropertyChanged("Wiki"); } 
    	}
    
     
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    	
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        
    }
}
