//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Launchbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public string FileName { get; set; }
        public string LBRegion { get; set; }
        public long Region_ID { get; set; }
        public long Release_ID { get; set; }
    
        public virtual Release Release { get; set; }
    }
}
