//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class Emulator : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emulator()
        {
    		Platforms = new HashSet<Platform>();
    		Platforms1 = new HashSet<Platform>();
        }
    
        private long _iD;
    	public long ID 
    	{ 
    		get { return _iD; } 
    		set { _iD = value; OnPropertyChanged("ID"); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { _title = value; OnPropertyChanged("Title"); } 
    	}
    
        private string _fileName;
    	public string FileName 
    	{ 
    		get { return _fileName; } 
    		set 
    		{
    			_fileName = value;
    			OnPropertyChanged("FileName");
    			OnPropertyChanged("FilePath");
    		} 
    	}
    
        private string _parameters;
    	public string Parameters 
    	{ 
    		get { return _parameters; } 
    		set { _parameters = value; OnPropertyChanged("Parameters"); } 
    	}
    
        private string _image;
    	public string Image 
    	{ 
    		get { return _image; } 
    		set { _image = value; OnPropertyChanged("Image"); } 
    	}
    
        private bool _isCrap;
    	public bool IsCrap 
    	{ 
    		get { return _isCrap; } 
    		set { _isCrap = value; OnPropertyChanged("IsCrap"); } 
    	}
    
        private string _website;
    	public string Website 
    	{ 
    		get { return _website; } 
    		set { _website = value; OnPropertyChanged("Website"); } 
    	}
    
        private Nullable<decimal> _rating;
    	public Nullable<decimal> Rating 
    	{ 
    		get { return _rating; } 
    		set { _rating = value; OnPropertyChanged("Rating"); } 
    	}
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual HashSet<Platform> Platforms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual HashSet<Platform> Platforms1 { get; set; }
     
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    	
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        
    }
}
