//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class GBGame : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GBGame()
        {
    		GBReleases = new List<GBRelease>();
        }
    
        private long _iD;
    	public long ID 
    	{ 
    		get { return _iD; } 
    		set { _iD = value; OnPropertyChanged("ID"); } 
    	}
    
        private Nullable<long> _gBPlatform_ID;
    	public Nullable<long> GBPlatform_ID 
    	{ 
    		get { return _gBPlatform_ID; } 
    		set { _gBPlatform_ID = value; OnPropertyChanged("GBPlatform_ID"); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { _title = value; OnPropertyChanged("Title"); } 
    	}
    
        private string _overview;
    	public string Overview 
    	{ 
    		get { return _overview; } 
    		set { _overview = value; OnPropertyChanged("Overview"); } 
    	}
    
        private string _developer;
    	public string Developer 
    	{ 
    		get { return _developer; } 
    		set { _developer = value; OnPropertyChanged("Developer"); } 
    	}
    
        private string _publisher;
    	public string Publisher 
    	{ 
    		get { return _publisher; } 
    		set { _publisher = value; OnPropertyChanged("Publisher"); } 
    	}
    
        private string _genre;
    	public string Genre 
    	{ 
    		get { return _genre; } 
    		set { _genre = value; OnPropertyChanged("Genre"); } 
    	}
    
        private Nullable<System.DateTime> _date;
    	public Nullable<System.DateTime> Date 
    	{ 
    		get { return _date; } 
    		set { _date = value; OnPropertyChanged("Date"); } 
    	}
    
        private string _boxURL;
    	public string BoxURL 
    	{ 
    		get { return _boxURL; } 
    		set { _boxURL = value; OnPropertyChanged("BoxURL"); } 
    	}
    
        private string _screenURL;
    	public string ScreenURL 
    	{ 
    		get { return _screenURL; } 
    		set { _screenURL = value; OnPropertyChanged("ScreenURL"); } 
    	}
    
    
        public virtual GBPlatform GBPlatform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<GBRelease> GBReleases { get; set; }
     
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    	
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        
    }
}
