//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class GBPlatform : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GBPlatform()
        {
    		GBGames = new List<GBGame>();
    		GBReleases = new List<GBRelease>();
        }
    
        private long _iD;
    	public long ID 
    	{ 
    		get { return _iD; } 
    		set { _iD = value; OnPropertyChanged("ID"); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { _title = value; OnPropertyChanged("Title"); } 
    	}
    
        private string _abbreviation;
    	public string Abbreviation 
    	{ 
    		get { return _abbreviation; } 
    		set { _abbreviation = value; OnPropertyChanged("Abbreviation"); } 
    	}
    
        private Nullable<long> _company;
    	public Nullable<long> Company 
    	{ 
    		get { return _company; } 
    		set { _company = value; OnPropertyChanged("Company"); } 
    	}
    
        private string _deck;
    	public string Deck 
    	{ 
    		get { return _deck; } 
    		set { _deck = value; OnPropertyChanged("Deck"); } 
    	}
    
        private string _price;
    	public string Price 
    	{ 
    		get { return _price; } 
    		set { _price = value; OnPropertyChanged("Price"); } 
    	}
    
        private Nullable<System.DateTime> _date;
    	public Nullable<System.DateTime> Date 
    	{ 
    		get { return _date; } 
    		set { _date = value; OnPropertyChanged("Date"); } 
    	}
    
        private System.DateTime _cacheDate;
    	public System.DateTime CacheDate 
    	{ 
    		get { return _cacheDate; } 
    		set { _cacheDate = value; OnPropertyChanged("CacheDate"); } 
    	}
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<GBGame> GBGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<GBRelease> GBReleases { get; set; }
     
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    	
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        
    }
}
