//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class GDBRelease : INotifyPropertyChanged
    {
        private long _iD;
    	public long ID 
    	{ 
    		get { return _iD; } 
    		set { _iD = value; OnPropertyChanged("ID"); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { _title = value; OnPropertyChanged("Title"); } 
    	}
    
        private long _gDBPlatform_ID;
    	public long GDBPlatform_ID 
    	{ 
    		get { return _gDBPlatform_ID; } 
    		set { _gDBPlatform_ID = value; OnPropertyChanged("GDBPlatform_ID"); } 
    	}
    
        private string _developer;
    	public string Developer 
    	{ 
    		get { return _developer; } 
    		set { _developer = value; OnPropertyChanged("Developer"); } 
    	}
    
        private string _publisher;
    	public string Publisher 
    	{ 
    		get { return _publisher; } 
    		set { _publisher = value; OnPropertyChanged("Publisher"); } 
    	}
    
        private string _players;
    	public string Players 
    	{ 
    		get { return _players; } 
    		set { _players = value; OnPropertyChanged("Players"); } 
    	}
    
        private string _overview;
    	public string Overview 
    	{ 
    		get { return _overview; } 
    		set { _overview = value; OnPropertyChanged("Overview"); } 
    	}
    
        private Nullable<decimal> _rating;
    	public Nullable<decimal> Rating 
    	{ 
    		get { return _rating; } 
    		set { _rating = value; OnPropertyChanged("Rating"); } 
    	}
    
        private string _genre;
    	public string Genre 
    	{ 
    		get { return _genre; } 
    		set { _genre = value; OnPropertyChanged("Genre"); } 
    	}
    
        private Nullable<System.DateTime> _date;
    	public Nullable<System.DateTime> Date 
    	{ 
    		get { return _date; } 
    		set { _date = value; OnPropertyChanged("Date"); } 
    	}
    
        private string _boxFrontURL;
    	public string BoxFrontURL 
    	{ 
    		get { return _boxFrontURL; } 
    		set { _boxFrontURL = value; OnPropertyChanged("BoxFrontURL"); } 
    	}
    
        private string _boxBackURL;
    	public string BoxBackURL 
    	{ 
    		get { return _boxBackURL; } 
    		set { _boxBackURL = value; OnPropertyChanged("BoxBackURL"); } 
    	}
    
        private string _bannerURL;
    	public string BannerURL 
    	{ 
    		get { return _bannerURL; } 
    		set { _bannerURL = value; OnPropertyChanged("BannerURL"); } 
    	}
    
        private string _screenURL;
    	public string ScreenURL 
    	{ 
    		get { return _screenURL; } 
    		set { _screenURL = value; OnPropertyChanged("ScreenURL"); } 
    	}
    
        private string _logoURL;
    	public string LogoURL 
    	{ 
    		get { return _logoURL; } 
    		set { _logoURL = value; OnPropertyChanged("LogoURL"); } 
    	}
    
        private Nullable<bool> _coop;
    	public Nullable<bool> Coop 
    	{ 
    		get { return _coop; } 
    		set { _coop = value; OnPropertyChanged("Coop"); } 
    	}
    
    
        public virtual GDBPlatform GDBPlatform { get; set; }
     
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    	
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        
    }
}
