//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LBEntities : DbContext
    {
        public LBEntities()
            : base("name=LBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LBGame> LBGames { get; set; }
        public virtual DbSet<LBImage> LBImages { get; set; }
        public virtual DbSet<LBPlatform> LBPlatforms { get; set; }
        public virtual DbSet<LBRelease> LBReleases { get; set; }
    }
}
