//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class OVGRelease : INotifyPropertyChanged
    {
        private long _iD;
    	public long ID 
    	{ 
    		get { return _iD; } 
    		set { _iD = value; OnPropertyChanged("ID"); } 
    	}
    
        private Nullable<long> _region_ID;
    	public Nullable<long> Region_ID 
    	{ 
    		get { return _region_ID; } 
    		set { _region_ID = value; OnPropertyChanged("Region_ID"); } 
    	}
    
        private long _oVGPlatform_ID;
    	public long OVGPlatform_ID 
    	{ 
    		get { return _oVGPlatform_ID; } 
    		set { _oVGPlatform_ID = value; OnPropertyChanged("OVGPlatform_ID"); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { _title = value; OnPropertyChanged("Title"); } 
    	}
    
        private string _overview;
    	public string Overview 
    	{ 
    		get { return _overview; } 
    		set { _overview = value; OnPropertyChanged("Overview"); } 
    	}
    
        private string _developer;
    	public string Developer 
    	{ 
    		get { return _developer; } 
    		set { _developer = value; OnPropertyChanged("Developer"); } 
    	}
    
        private string _publisher;
    	public string Publisher 
    	{ 
    		get { return _publisher; } 
    		set { _publisher = value; OnPropertyChanged("Publisher"); } 
    	}
    
        private string _genre;
    	public string Genre 
    	{ 
    		get { return _genre; } 
    		set { _genre = value; OnPropertyChanged("Genre"); } 
    	}
    
        private string _dateText;
    	public string DateText 
    	{ 
    		get { return _dateText; } 
    		set { _dateText = value; OnPropertyChanged("DateText"); } 
    	}
    
        private string _cRC;
    	public string CRC 
    	{ 
    		get { return _cRC; } 
    		set { _cRC = value; OnPropertyChanged("CRC"); } 
    	}
    
        private string _mD5;
    	public string MD5 
    	{ 
    		get { return _mD5; } 
    		set { _mD5 = value; OnPropertyChanged("MD5"); } 
    	}
    
        private string _sHA1;
    	public string SHA1 
    	{ 
    		get { return _sHA1; } 
    		set { _sHA1 = value; OnPropertyChanged("SHA1"); } 
    	}
    
        private string _size;
    	public string Size 
    	{ 
    		get { return _size; } 
    		set { _size = value; OnPropertyChanged("Size"); } 
    	}
    
        private string _header;
    	public string Header 
    	{ 
    		get { return _header; } 
    		set { _header = value; OnPropertyChanged("Header"); } 
    	}
    
        private string _language;
    	public string Language 
    	{ 
    		get { return _language; } 
    		set { _language = value; OnPropertyChanged("Language"); } 
    	}
    
        private string _serial;
    	public string Serial 
    	{ 
    		get { return _serial; } 
    		set { _serial = value; OnPropertyChanged("Serial"); } 
    	}
    
        private string _boxFrontURL;
    	public string BoxFrontURL 
    	{ 
    		get { return _boxFrontURL; } 
    		set { _boxFrontURL = value; OnPropertyChanged("BoxFrontURL"); } 
    	}
    
        private string _boxBackURL;
    	public string BoxBackURL 
    	{ 
    		get { return _boxBackURL; } 
    		set { _boxBackURL = value; OnPropertyChanged("BoxBackURL"); } 
    	}
    
        private string _referenceURL;
    	public string ReferenceURL 
    	{ 
    		get { return _referenceURL; } 
    		set { _referenceURL = value; OnPropertyChanged("ReferenceURL"); } 
    	}
    
        private string _referenceImageURL;
    	public string ReferenceImageURL 
    	{ 
    		get { return _referenceImageURL; } 
    		set { _referenceImageURL = value; OnPropertyChanged("ReferenceImageURL"); } 
    	}
    
        private Nullable<System.DateTime> _date;
    	public Nullable<System.DateTime> Date 
    	{ 
    		get { return _date; } 
    		set { _date = value; OnPropertyChanged("Date"); } 
    	}
    
    
        public virtual OVGPlatform OVGPlatform { get; set; }
        public virtual Region Region { get; set; }
     
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    	
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        
    }
}
