//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class Rom : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rom()
        {
    		Releases = new List<Release>();
        }
    
        private long _iD;
    	public long ID 
    	{ 
    		get { return _iD; } 
    		set { _iD = value; OnPropertyChanged("ID"); } 
    	}
    
        private long _platform_ID;
    	public long Platform_ID 
    	{ 
    		get { return _platform_ID; } 
    		set { _platform_ID = value; OnPropertyChanged("Platform_ID"); } 
    	}
    
        private string _title;
    	public string Title 
    	{ 
    		get { return _title; } 
    		set { _title = value; OnPropertyChanged("Title"); } 
    	}
    
        private string _cRC32;
    	public string CRC32 
    	{ 
    		get { return _cRC32; } 
    		set { _cRC32 = value; OnPropertyChanged("CRC32"); } 
    	}
    
        private string _mD5;
    	public string MD5 
    	{ 
    		get { return _mD5; } 
    		set { _mD5 = value; OnPropertyChanged("MD5"); } 
    	}
    
        private string _sHA1;
    	public string SHA1 
    	{ 
    		get { return _sHA1; } 
    		set { _sHA1 = value; OnPropertyChanged("SHA1"); } 
    	}
    
        private string _size;
    	public string Size 
    	{ 
    		get { return _size; } 
    		set { _size = value; OnPropertyChanged("Size"); } 
    	}
    
        private string _source;
    	public string Source 
    	{ 
    		get { return _source; } 
    		set { _source = value; OnPropertyChanged("Source"); } 
    	}
    
        private string _fileName;
    	public string FileName 
    	{ 
    		get { return _fileName; } 
    		set 
    		{
    			_fileName = value;
    			OnPropertyChanged("FileName");
    			OnPropertyChanged("FilePath");
    		} 
    	}
    
    
        public virtual Platform Platform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Release> Releases { get; set; }
     
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    	
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        
    }
}
