//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGDBREGION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VGDBREGION()
        {
            this.VGDBRELEASES = new HashSet<VGDBRELEAS>();
        }
    
        public long regionID { get; set; }
        public string regionName { get; set; }
        public string Datomatic { get; set; }
        public string ID_GB { get; set; }
        public string Title_GB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VGDBRELEAS> VGDBRELEASES { get; set; }
    }
}
