//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGDBROM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VGDBROM()
        {
            this.VGdbreleaseS = new HashSet<VGDBRELEAS>();
        }
    
        public long romID { get; set; }
        public long systemID { get; set; }
        public long regionID { get; set; }
        public string romHashCRC { get; set; }
        public string romHashMd5 { get; set; }
        public string romHashSha1 { get; set; }
        public Nullable<long> romSize { get; set; }
        public string romFileName { get; set; }
        public string romExtensionlessFileName { get; set; }
        public string romSerial { get; set; }
        public string romHeader { get; set; }
        public string romLanguage { get; set; }
        public string TEMPromRegion { get; set; }
        public string romDumpSource { get; set; }
        public Nullable<long> CloneOf { get; set; }
    
        public virtual VGdbplatform VGdbplatform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VGDBRELEAS> VGdbreleaseS { get; set; }
    }
}
